
services:
  postgres:
    image: postgres:16-alpine
    container_name: invo-app-db
    environment:
      POSTGRES_USER: invo_user
      POSTGRES_PASSWORD: invo_password_123
      POSTGRES_DB: invo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
